lms_hub/views/calendar.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

calendar = Blueprint("calendar", __name__)


@calendar.route("/calendar")
@login_required
def calendar_page():
    return render_template("lms/calendar.html", active_nav="calendar")

lms_hub/views/classcard.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

classcard = Blueprint("classcard", __name__)


@classcard.route("/classcard")
@login_required
def classcard_page():
    return render_template("lms/classcard.html", active_nav="classcard")

lms_hub/views/dashboard.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

dashboard = Blueprint("dashboard", __name__)


@dashboard.route("/dashboard")
@login_required
def dashboard_page():
    return render_template("lms/dashboard.html", active_nav="dashboard")
    # uvle_islinked = "uvle" in current_user.accounts and current_user.accounts["uvle"].token != ""
    # gclass_islinked = "gclass" in current_user.accounts

    # # User is returning, show normal dashboard
    # return render_template(
    #     "dashboard.html",
    #     uvle_islinked=uvle_islinked,
    #     gclass_islinked=gclass_islinked
    # )

lms_hub/views/login.py
from os import environ
from urllib.parse import urljoin, urlparse

from lms_hub.models.profile import from_google_jwt

from flask import (Blueprint, current_app, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_user
from google.auth.exceptions import GoogleAuthError
from google.auth.transport import requests
from google.oauth2 import id_token

login = Blueprint("login", __name__)

def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

@login.route("/login", methods=["GET"])
def login_page():
    # Redirect to dashboard if already logged in
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.dashboard_page"))

    return render_template(
        "lms/login.html",
        domain=environ["DOMAIN"],
        google_client_id=current_app.config["GOOGLE_CLIENT_ID"],
    )

@login.route("/login", methods=["POST"])
def login_form():
    db = current_app.config["DB"]

    if "g_csrf_token" not in request.form:
        
        return "CSRF token missing", 400
    csrf_cookie = request.cookies.get("g_csrf_token")
    if not csrf_cookie or csrf_cookie != request.form["g_csrf_token"]:
        return "CSRF cookie missing", 400

    try:
        id_info = id_token.verify_oauth2_token(
            request.form["credential"],
            requests.Request(),
            current_app.config["GOOGLE_CLIENT_ID"],
        )
    except (ValueError, GoogleAuthError) as e:
        return f"Invalid JWT: {str(e)}", 400
    else:
        if not id_info["email_verified"]:
            return "Email not verified", 400

    email = id_info["email"]
    matching_user = db.lookup_user_by_email(email)
    if matching_user is None:
        if not id_info["email_verified"]:
            return "Email not verified", 400

        matching_user = from_google_jwt(id_info)
        db.add_user(matching_user)

    # Log in
    login_user(matching_user)

    # Redirect to the next page
    next_url = request.args.get("next")
    if not is_safe_url(next_url):
        return "Unsafe redirect URL", 400
    return redirect(next_url or url_for("dashboard.dashboard_page"))

lms_hub/views/settings.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

settings = Blueprint("settings", __name__)


@settings.route("/settings")
@login_required
def settings_page():
    return render_template("lms/settings.html", active_nav="settings")

templates/lms/base-logged-in.html
{% extends "lms/base.html" %}

{% block body %}
<div class="d-flex" id="wrapper">
    <!-- Side bar -->

    <div class="bg-white" id="sidebar-wrapper">
        <div
            class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase">
            LMS Backpack
        </div>

        <div class="list-group list-group-flush my-3">
            <a
                href="{{ url_for('dashboard.dashboard_page') }}"
                class="{% if active_nav == 'dashboard' %}active{% endif %} list-group-item list-group-item-action bg-transparent second-text fw-bold button">
                <h4>Dashboard</h4>
            </a>
            <a
                href="{{ url_for('calendar.calendar_page') }}"
                class="{% if active_nav == 'calendar' %}active{% endif %} list-group-item list-group-item-action bg-transparent second-text fw-bold button">
                <h4>Calendar</h4>
            </a>
            <a
                href="{{ url_for('classcard.classcard_page') }}"
                class="{% if active_nav == 'classcard' %}active{% endif %} list-group-item list-group-item-action bg-transparent second-text fw-bold button">
                <h4>Class Cards</h4>
            </a>
            <a
                href="{{ url_for('settings.settings_page') }}"
                class="{% if active_nav == 'settings' %}active{% endif %} list-group-item list-group-item-action bg-transparent second-text fw-bold button">
                <h4>Settings</h4>
            </a>
        </div>
    </div>
    <!-- End Side bar -->

    <div id="page-content-wrapper">
        <!-- Start Navbar -->
        <nav
            class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
            <div class="d-flex align-items-center">
                <i
                    class="fas fa-align-left primary-text fs-4 me-3"
                    id="menu-toggle"></i>
                <h2 class="fs-2 m-0">{% block page_heading %}{% endblock %}</h2>
            </div>

            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <!-- End Navbar -->

        {% block content %} {% endblock %}
    </div>
    <!--End content-->
</div>
{% endblock %}

templates/lms/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock %} | LMS Backpack</title>

        <!-- Bootstrap CSS -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
            crossorigin="anonymous" />

        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
            rel="stylesheet" />

        <!-- Style -->
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='styles/base.css') }}" />
        {% block head %} {% endblock %}
    </head>
    <body>
        {% block body %} {% endblock %}
        <!-- Bootstrap JS -->

        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <!-- <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script> -->
        <!-- <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script> -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
            crossorigin="anonymous"></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
            integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
            crossorigin="anonymous"></script>

        {% block scripts %} {% endblock %}
    </body>
</html>

templates/lms/calendar.html
{% extends "lms/base-logged-in.html" %}
{% block title %}Calendar{% endblock %}
{% block head %}{% endblock %}
{% block page_heading %}Calendar{% endblock %}
{% block content %}
<div class="d-flex" id="app">
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='scripts/calendar.js') }}"></script>
<script>
    var el = document.getElementById("wrapper");
    var toggleButton = document.getElementById("menu-toggle");

    toggleButton.onclick = function () {
        el.classList.toggle("toggled");
    };
</script>
{% endblock %}

templates/lms/classcard.html
{% extends "lms/base-logged-in.html" %}
{% block title %}Classcards{% endblock %}
{% block head %}{% endblock %}
{% block page_heading %}Class Cards{% endblock %}
{% block content %}
<div class="d-flex align-items-center">
    <h2 id = "owner" class="fs-2 m-2"></h2>
    <h2 class="fs-2 m-2">{{current_user['name']}} !</h2>
</div>
<div class="container-fluid px-4">
    <div class="row g-3 my-2">
        <h2 class="fs-3">Your classes</h2>
        <div class="container mx-auto">
            <div class="col mx-auto">
                <div id="deadlines" class="row mx-auto"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
    var el = document.getElementById("wrapper");
    var toggleButton = document.getElementById("menu-toggle");

    toggleButton.onclick = function () {
        el.classList.toggle("toggled");
    };
</script>
<script src="{{ url_for('static', filename='scripts/classcard.js') }}"></script>
{% endblock %}

templates/lms/dashboard.html
{% extends "lms/base-logged-in.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}{% endblock %}
{% block page_heading %}Dashboard{% endblock %}
{% block content %}

<div class="d-flex align-items-center">
    <h2 id = "owner" class="fs-2 m-2"></h2>
    <h2 class="fs-2 m-2">{{current_user['name']}} !</h2>
</div>

<p id="assignmentNumberUvle" class="fs-2 m-2 text-danger text-center"></p>
<p id="assignmentNumberGclass" class="fs-2 m-2 text-danger text-center"></p>

<section id="UpcomingEvents">
<h2 class="text-center my-5">Upcoming events</h2>
<div class="container mx-auto">
    <div class="col mx-auto">
        <div id="deadlines" class="row mx-auto"></div>
    </div>
</div>
</section>
{% endblock %}
{% block scripts %}
<script>
    var el = document.getElementById("wrapper");
    var toggleButton = document.getElementById("menu-toggle");

    toggleButton.onclick = function () {
        el.classList.toggle("toggled");
    };
</script>
<script src="{{ url_for('static', filename='scripts/dashboard.js') }}"></script>

{% endblock %}

templates/lms/login-uvle.html
{% extends "lms/base.html" %}
{% block title %}Link UVLe{% endblock %}
{% block head %}{% endblock %}
{% block body %}
<section class="vh-100" style="background-color: #063149">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 2rem">
                    <div class="row g-0">
                        <div
                            class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div
                                class="card-body p-4 p-lg-5 text-black bg-white">
                                <form name="signinForm">
                                    <div
                                        class="d-flex align-items-center mb-3 pb-1">
                                        <span class="h1 fw-bold mb-0"
                                            >Connect your UVLê account</span
                                        >
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input
                                            type="text"
                                            id="username"
                                            class="form-control form-control-lg"
                                            placeholder="Enter Username"
                                            required />
                                        <label class="form-label" for="username"
                                            >Email</label
                                        >
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input
                                            type="password"
                                            id="password"
                                            class="form-control form-control-lg"
                                            placeholder="Enter Password"
                                            required />
                                        <label class="form-label" for="password"
                                            >Password</label
                                        >
                                    </div>

                                    <div class="pt-1 mb-4">
                                        <button
                                            class="btn btn-dark btn-lg btn-block"
                                            type="submit">
                                            Connect
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
<script>
    var el = document.getElementById("wrapper");
    var toggleButton = document.getElementById("menu-toggle");

    toggleButton.onclick = function () {
        el.classList.toggle("toggled");
    };
</script>
<script
    defer
    src="{{ url_for('static', filename='scripts/login-uvle.js')}}"></script>
{% endblock %}

templates/lms/login.html
{% extends "lms/base.html" %}
{% block title %}Signin{% endblock %}
{% block head %}{% endblock %}
{% block body %}
<section class="vh-100" style="background-color: #063149">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img
                                src="https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?cs=srgb&dl=pexels-matheus-bertelli-2905238.jpg&fm=jpg"
                                alt="image from pexels.com taken by Matheus Bertelli"
                                class="img-fluid"
                                style="border-radius: 1rem 0 0 1rem" />
                        </div>
                        <div
                            class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div
                                class="card-body p-4 p-lg-5 text-black bg-white">
                                <form name="signinForm" action="" method="POST">
                                    <div
                                        class="d-flex align-items-center mb-3 pb-1">
                                        <span class="h1 fw-bold mb-0"
                                            >LMS Backpack</span
                                        >
                                    </div>

                                    <h5
                                        class="fw-normal mb-3 pb-3"
                                        style="letter-spacing: 1px">
                                        Sign into your account
                                    </h5>


                                    <div class="google-signin">
                                        <div
                                            class="g_id_signin"
                                            data-type="standard"
                                            data-size="large"
                                            data-theme="outline"
                                            data-text="signin_with"
                                            data-shape="pill"
                                            data-logo_alignment="left"></div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div
    id="g_id_onload"
    data-client_id="{{ google_client_id }}"
    data-login_uri="{{ domain }}/login"
    data-prompt_parent_id="g_id_onload"
    data-auto_prompt="true"
    data-context="signin"
    data-ux_mode="popup"></div>
{% endblock %}
{% block scripts %}
<script>
    var el = document.getElementById("wrapper");
    var toggleButton = document.getElementById("menu-toggle");

    toggleButton.onclick = function () {
        el.classList.toggle("toggled");
    };
</script>
<script src="https://accounts.google.com/gsi/client" async defer></script>
{% endblock %}

templates/lms/settings.html
{% extends "lms/base-logged-in.html" %}
{% block title %}Settings{% endblock %}
{% block head %}{% endblock %}
{% block page_heading %}Settings{% endblock %}
{% block content %}
<div class="container-fluid px-4">
    <div class="row g-3 my-1">
        <div class="col">
            <div class="p-1 d-flex align-items-center">
                <p class="fs-2 m-2 text-light">Link UVLê</p>
                <button
                    class="btn btn-link"
                    onClick="location.href='link/uvle'">
                    <i
                        class="fas m-2 fa-external-link-alt fs-4 primary-text"></i>
                </button>
            </div>
            <div class="p-1 d-flex align-items-center">
                <p class="fs-2 m-2 text-light">Link Google Classroom</p>
                <button
                    class="btn btn-link"
                    onClick="location.href='link/gclass'">
                    <i
                        class="fas m-2 fa-external-link-alt fs-4 primary-text"></i>
                </button>
            </div>
            <hr />
        </div>
    </div>
</div>

<div class="container-fluid px-4">
    <div class="row g-3 my-2">
        <h2 class="fs-3">Linked accounts</h2>
        <div class="col-md-3 d-grid gap-4">
            {% if 'uvle' in current_user['accounts'] %}
                <div class="p-1 d-flex align-items-center">
                    <div class="rounded-circle uvle-image m-0">&nbsp;</div>     
                    <p class="fs-3 m-2 text-light">
                        {{ current_user['accounts']['uvle']['username']}}
                    </p>
                    <a class = "m-2" href="{{ url_for('link-uvle.logout_post') }}"
                        >Unlink</a>
                </div>
            {% endif %}  
            {% if 'gclass' in current_user['accounts'] %}
                <div class="p-1 d-flex align-items-center">
                        <div class="rounded-circle googleclassroom-image m-0">&nbsp;</div>     
                        <p class="fs-3 m-2 text-light">
                            {{ current_user['accounts']['gclass']['email']}}
                        </p>
                        <a class = "m-2" href="{{ url_for('link-gclass.logout_post') }}"
                            >Unlink</a>
                </div>  
            {% endif %}                   
        </div>
    </div>
</div>

<button type ="button"
                class="m-4 btn btn-primary btn-sm"
                onClick="">Logout
</button>


{% endblock %}
{% block scripts %}
<script>
    var el = document.getElementById("wrapper");
    var toggleButton = document.getElementById("menu-toggle");

    toggleButton.onclick = function () {
        el.classList.toggle("toggled");
    };
</script>
{% endblock %}

templates/lms/signin screen (to be connectd).html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LMS Backpack</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="styles.css" />
</head>
<body>
    <section class="vh-100" style="background-color: #063149;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?cs=srgb&dl=pexels-matheus-bertelli-2905238.jpg&fm=jpg"
                      alt="image from pexels.com taken by Matheus Bertelli" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black bg-white">
      
                      <form>
      
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <span class="h1 fw-bold mb-0">LMS Backpack</span>
                        </div>
      
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>
      
                        <div class="form-outline mb-4">
                          <input type="email" id="form2Example17" class="form-control form-control-lg" />
                          <label class="form-label" for="form2Example17">Email address</label>
                        </div>
      
                        <div class="form-outline mb-4">
                          <input type="password" id="form2Example27" class="form-control form-control-lg" />
                          <label class="form-label" for="form2Example27">Password</label>
                        </div>
      
                        <div class="pt-1 mb-4">
                          <button class="btn btn-dark btn-lg btn-block" type="button">Login</button>
                        </div>
      
                        <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="#!"
                            style="color: #393f81;">Register here</a></p>
                      </form>
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>


    
    <script src="js/bootstrap.js"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
    <script src="dashboard_script/dashboard.js"></script>
    <script type="text/javascript" src="dashboard.json"></script>
</body>
</html>